### ISSUE TITLE
Skeleton HTML To Start With

### ISSUE THREAD

**Issue by ascii-dev** [nebrelbug/awesome-for-beginners#1]
Hey @nebrelbug, can you, uhm, push a skeleton html/css code to start with so we can all pull that in and get started working. I have lots of free time on my hand now and I feel I should spend it working on this.

**Comment by bgub** [comment]
Sure! Does what I've done work @ascii-dev?

**Comment by ascii-dev** [comment]
It's cool, I'll arrange it into folders now and push back... I think we should use bootstrap, what do you think?

**Comment by bgub** [comment]
I think that sounds good. I haven't used much Bootstrap, but I'll touch up on it :)

**Comment by ascii-dev** [comment]
Great! I'm creating a pull request on the updated structure including Bootstrap now...
